version: "3.7"

services:
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - '5672:5672'
      - '15672:15672'
      
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: always
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686